# Generated by Django 2.2.dev20181004154227 on 2018-10-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uq_event',
        ),
    ]
