# Generated by Django 2.2.dev20181004154227 on 2018-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0002_auto_20181006_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='uq_event',
            name='uuid',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
