# Generated by Django 2.2.dev20181004154227 on 2018-10-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0004_uq_event_unix_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uq_event',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
