# Generated by Django 2.2.dev20181004154227 on 2018-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0003_uq_event_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uq_event',
            name='unix_tmp',
            field=models.FloatField(default=1000000000.0),
        ),
    ]
