# Generated by Django 2.2.dev20181004154227 on 2018-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uq_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evt_name', models.CharField(max_length=130)),
                ('evt_place', models.CharField(blank=True, max_length=130)),
                ('evt_exact_time', models.CharField(blank=True, max_length=130)),
                ('evt_duration', models.CharField(blank=True, max_length=130)),
                ('evt_done', models.BooleanField(default=False)),
                ('evt_type', models.CharField(choices=[('RD', 'reminder'), ('DL', 'deadline'), ('AV', 'activity')], default='RD', max_length=2)),
            ],
        ),
    ]
